### ISSUE TITLE
Missing code of the PCD alignment pre-processing part.

### ISSUE THREAD

**Issue by Matthew-CQ** [NunoDuarte/3DSGrasp#2]
Hi,

Thank you for your excellent work! I found there isn't a code for PCD alignment pre-processing in testing mode. And do we need to rotate partial pcd in real pcd captured by depth camera such as real-sense to meet the requirement of mode input? Could you please share the detailed code with us? Thanks.

Best Regards,

Matthew

**Comment by NunoDuarte** [comment]
Hi,

Thanks for showing interest in our work. We are aware of this and are trying to update the code and documentation in order to run the network. 

As for the question 
> And do we need to rotate partial pcd in real pcd captured by depth camera such as real-sense to meet the requirement of mode input? 

I'm not sure I understand. We don't do any rotation of the partial PCD from the real-sense camera. The camera is on the wrist of the robot and the perspective that the robot sees the object (i.e. orientation) is what is sent to the completion network.

**Comment by NunoDuarte** [comment]
Just to inform that the code has been updated and you can now train your own network or run our pertained network for completion.
